### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by banosl** [banosl/recipe_keeper#51]
This is the top level of what I want this app to do as part of minimal viable product
- [x] Oauth2 sign in with Google
- [ ] Sessions
- [ ] Library Index Page
  - [x] Display library books in a table
  - [ ] Filters
  - [ ] Sort by
- [x] Add cookbooks
  - [x] New cookbook form
  - [x] User can select from a list of 5 matches for cookbook from the Google Books API
- [ ] Cookbooks show page
  - [ ] List recipes in a table
  - [ ] Filters
  - [ ] Sort by
  - [ ] Add recipe
  - [ ] Recipe show page
    - [ ] Edit recipe
    - [ ] Delete recipe
